version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile  # Itt adod meg a pontos elérési utat!
    volumes:
      - ./frontend/build:/app/frontend/build
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile  # Itt is pontosítsd az útvonalat!
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: codefuson_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
